version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha123789
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
  
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "5000:3000"
    depends_on:
      - db
    # env_file:
    #     - .env